config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploaders :photos, PhotosUploader
	serialize :photos, JSON
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  def index
  	@products = Product.all
  end
  def new
  @product = Product.new
  end
  def create
  	@product = current_user.products.build(product_params)
  	if @product.save
  		redirect_to  root_path
  	end
   
   
  end
  def show
  	@product = Product.find_by(id:params[:id])
  end
  def edit
  	
  end
  def update
  	
  end
  def destroy
  	
  end
   private
    def product_params
      params.require(:product).permit(:user_id, :title, :description, :price, {photos: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

<%= link_to "login", new_user_session_path %> <br>
<hr>

<% if user_signed_in?%>

<%= link_to "create new product", new_product_path %> <br>
<hr>

<% @products.each do | product | %> 
	<%= product.title %><br/>
	<%= product.description %><br/>
	<%= product.price %><br/></p>

	<% product.photos.each do | photo | %> 
		<%= image_tag(photo.url, size: "200x100")%>	<br> 
	<% end %>
	
	<p><%= link_to "Read more", product_path(product.id) %></p> 
	<hr>
<% end %>
<% end %>

app/views/products/new.html.erb
<%= form_for @product, url: products_path do |f| %>
title<br>
<%= f.text_field :title %><br>
description<br>
<%= f.text_field :description %><br>
price<br>
<%= f.text_field :price %><br>
<%= f.file_field :photos, multiple: true %><br>
<%= f.submit "Create" %>
<% end %>

app/views/products/show.html.erb
title: <%= @product.title %><br/>
description: <%= @product.description %><br/>
price: <%= @product.price %><br/>

<%= link_to "Back", root_path%><br/>